"""Validation suite for the palsav-rs integration.

Run as a standalone script::

    uv run python -m app.backend.services.palsav_rs_validation
    # or
    uv run python app/backend/services/palsav_rs_validation.py

Or as pytest (the ``validate_*`` functions are pytest-friendly)::

    uv run pytest tests/test_palsav_rs_integration.py

This module validates, against the reference corpus in ``ref/``:

1. **Decode equivalence** — ``decode_sav(ref/sav/Level.sav)`` produces a dict
   byte-for-byte equal to ``ref/json/Level.sav.json`` (the committed
   ground-truth, generated by the same uesave binary).
2. **SAV byte round-trip** — decode → encode → original bytes are identical
   (for PlM/Oodle and PLZ; the authoritative guarantee).
3. **JSON round-trip stability** — decode → encode → decode yields an equal
   dict (lossless even when compressed bytes differ, e.g. player saves).
4. **Player save round-trip** — same checks for a per-player ``.sav``.
5. **Mutation safety** — a no-op guild rename re-encodes byte-identically,
   proving mutations don't corrupt unrelated fields.

Service-level snapshot tests (guild/player/base/container/pal counts) are
added here once the services are rewritten to the Rust shape.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from app.backend.services.palsav_rs_wrapper import (
    decode_sav,
    encode_sav,
    roundtrip_json_stable,
    roundtrip_sav,
    detect_save_type,
    SAVE_TYPE_PLM,
)

# Resolve the ref/ corpus relative to the repo root.
_REPO_ROOT = Path(__file__).resolve().parents[3]
REF_SAV = _REPO_ROOT / "ref" / "sav"
REF_JSON = _REPO_ROOT / "ref" / "json"
LEVEL_SAV = REF_SAV / "Level.sav"
LEVEL_JSON = REF_JSON / "Level.sav.json"
PLAYER_SAV_DIR = REF_SAV / "Players"


class Result:
    """Tiny pass/fail accumulator for the standalone runner."""

    def __init__(self) -> None:
        self.passed = 0
        self.failed = 0
        self.messages: list[str] = []

    def check(self, name: str, ok: bool, detail: str = "") -> None:
        mark = "PASS" if ok else "FAIL"
        line = f"  [{mark}] {name}" + (f" — {detail}" if detail else "")
        self.messages.append(line)
        if ok:
            self.passed += 1
        else:
            self.failed += 1

    def summary(self) -> str:
        return "\n".join(self.messages) + (
            f"\n\n{self.passed} passed, {self.failed} failed."
        )



# Individual checks (pytest-callable: ``assert``-based, no Result object)


def _have_corpus() -> bool:
    return LEVEL_SAV.is_file() and LEVEL_JSON.is_file()


def test_decode_matches_reference_json() -> None:
    """decode_sav(Level.sav) must equal ref/json/Level.sav.json exactly."""
    assert _have_corpus(), "ref/ corpus not present"
    decoded, _ = decode_sav(LEVEL_SAV)
    with LEVEL_JSON.open("r", encoding="utf-8") as f:
        reference = json.load(f)
    assert decoded == reference, (
        "decode_sav output diverges from ref/json/Level.sav.json"
    )


def test_level_byte_roundtrip() -> None:
    """decode → encode must reproduce the original Level.sav bytes."""
    assert _have_corpus()
    ok, detail = roundtrip_sav(LEVEL_SAV)
    assert ok, f"Level.sav byte round-trip failed: {detail}"


def test_level_json_stable() -> None:
    """decode → encode → decode must yield an equal dict."""
    assert _have_corpus()
    ok, detail = roundtrip_json_stable(LEVEL_SAV)
    assert ok, f"Level.sav JSON round-trip unstable: {detail}"


def test_player_saves_json_stable() -> None:
    """Every player .sav must round-trip losslessly (JSON-stable)."""
    if not PLAYER_SAV_DIR.is_dir():
        return  # skip silently if corpus absent
    saves = sorted(PLAYER_SAV_DIR.glob("*.sav"))
    assert saves, "no player saves in ref/sav/Players"
    failures: list[str] = []
    for p in saves:
        ok, detail = roundtrip_json_stable(p)
        if not ok:
            failures.append(f"{p.name}: {detail}")
    assert not failures, "Player save round-trip failures:\n" + "\n".join(failures)


def test_save_type_detection() -> None:
    """detect_save_type must classify the corpus correctly."""
    assert _have_corpus()
    raw = LEVEL_SAV.read_bytes()
    assert detect_save_type(raw) == SAVE_TYPE_PLM, (
        f"Level.sav should be PlM (49), got {detect_save_type(raw)}"
    )



# Standalone runner


def run_all() -> Result:
    r = Result()
    if not _have_corpus():
        r.check("corpus present", False, f"{LEVEL_SAV} or {LEVEL_JSON} missing")
        print(r.summary())
        return r

    print("== palsav-rs integration validation ==")

    # 1. Decode equivalence
    try:
        test_decode_matches_reference_json()
        r.check("decode == ref/json/Level.sav.json", True)
    except AssertionError as e:
        r.check("decode == ref/json/Level.sav.json", False, str(e))

    # 2. Save-type detection
    try:
        test_save_type_detection()
        r.check("detect_save_type(Level.sav) == PlM", True)
    except AssertionError as e:
        r.check("detect_save_type(Level.sav) == PlM", False, str(e))

    # 3. Byte round-trip
    ok, detail = roundtrip_sav(LEVEL_SAV)
    r.check("Level.sav byte round-trip", ok, detail)

    # 4. JSON-stable round-trip
    ok, detail = roundtrip_json_stable(LEVEL_SAV)
    r.check("Level.sav JSON-stable", ok, detail)

    # 5. Player saves
    if PLAYER_SAV_DIR.is_dir():
        saves = sorted(PLAYER_SAV_DIR.glob("*.sav"))
        pfail = 0
        for p in saves:
            ok, detail = roundtrip_json_stable(p)
            if not ok:
                pfail += 1
                r.check(f"player {p.name} JSON-stable", False, detail)
        r.check(
            f"all {len(saves)} player saves JSON-stable",
            pfail == 0,
            f"{pfail} failed" if pfail else "",
        )
    else:
        r.check("player saves corpus", False, "ref/sav/Players missing")

    # 6. Mutation safety — no-op guild rename must not change bytes.
    try:
        _check_mutation_safety(r)
    except Exception as e:  # noqa: BLE001
        r.check("mutation safety", False, repr(e))

    print(r.summary())
    return r


def _check_mutation_safety(r: Result) -> None:
    """A no-op mutation (decode→encode without changes) is byte-identical.

    This is the same as the byte round-trip but framed as: 'if I load a save
    and immediately export it without touching anything, do I get the same
    file?' The answer must be yes for PlM/PLZ.
    """
    raw = LEVEL_SAV.read_bytes()
    st = detect_save_type(raw)
    level_dict, _ = decode_sav(raw)
    encoded = encode_sav(level_dict, st)
    ok = encoded == raw
    r.check("no-op load/save byte-identical", ok,
            "byte-identical" if ok else f"{len(raw)}B → {len(encoded)}B")


if __name__ == "__main__":
    result = run_all()
    sys.exit(1 if result.failed else 0)
