/**
 * diff-logger.ts — OpenCode local plugin
 *
 * Maintains .opencode/changes.md as a human-readable changelog of every file
 * change made by OpenCode sessions.
 *
 * HOW IT WORKS
 *  - Hooks the `session.diff` event (fires whenever a session's working-tree
 *    diff changes).
 *  - Writes ONE rolling entry per session — identified by sessionID — so the
 *    file doesn't fill with near-duplicate incremental snapshots. Each session
 *    gets a single entry that updates in place as it makes more changes.
 *  - Newest session at the top; each entry lists every touched file with
 *    +/- line counts.
 *
 * No external deps: uses Bun file APIs (always available under opencode).
 */
import type { Plugin } from "@opencode-ai/plugin";

const REL = ".opencode/changes.md";

const HEADER = [
  "# OpenCode Change Log",
  "",
  "Auto-generated by `.opencode/plugins/diff-logger.ts`.",
  "One rolling entry per session (updated in place on every `session.diff` event).",
  "",
  "---",
  "",
].join("\n");

/** Format a single FileDiff as a markdown list item. */
function fmtFile(d: {
  file: string;
  before?: string;
  after?: string;
  additions?: number;
  deletions?: number;
}): string {
  const add = d.additions ?? 0;
  const del = d.deletions ?? 0;
  // Rename if before/after differ and both present
  const renamed = d.before && d.after && d.before !== d.after;
  // Pure addition (new file) if additions but no deletions
  const tag = renamed ? "R" : add > 0 && del === 0 ? "A" : "M";
  return `- [${tag}] \`${d.file}\` (+${add}/-${del})`;
}

export const DiffLogger: Plugin = async ({ directory, client }) => {
  const fullPath = `${directory}/${REL}`;

  return {
    event: async ({ event }) => {
      if (event.type !== "session.diff") return;

      const { sessionID, diff } = (
        event.properties as { sessionID: string; diff: any[] }
      );
      if (!Array.isArray(diff) || diff.length === 0) return;

      // Resolve a friendly session title (best-effort; ignore failures)
      let title = sessionID.slice(-12);
      try {
        const res = await client.session.get({ sessionID });
        const t = (res?.data ?? res)?.title;
        if (t && String(t).trim()) title = String(t).trim();
      } catch {
        /* keep fallback */
      }

      const ts = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";
      const lines = diff
        .slice()
        .sort((a, b) => String(a.file).localeCompare(String(b.file)))
        .map(fmtFile);
      const totals = diff.reduce(
        (acc, d) => {
          acc.a += d.additions ?? 0;
          acc.d += d.deletions ?? 0;
          return acc;
        },
        { a: 0, d: 0 },
      );

      // Build the entry. The trailing HTML comment carries the sessionID for
      // dedup — invisible in rendered markdown but machine-parseable.
      const entry = [
        `## ${ts} — ${title}  <!-- ${sessionID} -->`,
        "",
        `${diff.length} file(s) changed — +${totals.a}/-${totals.d}`,
        "",
        ...lines,
        "",
      ].join("\n");

      // Read current file (if any) and split header from existing entries.
      let body = "";
      try {
        body = await Bun.file(fullPath).text();
      } catch {
        /* file doesn't exist yet */
      }

      const sep = "\n---\n";
      const sepIdx = body.indexOf(sep);
      const existing = sepIdx >= 0 ? body.slice(sepIdx + sep.length).trimStart() : "";

      // Split existing entries and drop any stale entry for THIS session.
      const entries = existing
        .split(/\n(?=## )/)
        .map((e) => e.trim())
        .filter((e) => e.length > 0 && !e.includes(`<!-- ${sessionID} -->`));

      // Newest first.
      const out = HEADER + "\n" + entry + (entries.length ? "\n" + entries.join("\n\n") + "\n" : "\n");

      await Bun.write(fullPath, out);
    },
  };
};

export default DiffLogger;
